name: quote-box
author: Connor Kuo <touch@rnmeow.com>
description: Get a quote and push to GitHub Gist.

branding:
  icon: file-text
  color: yellow

runs:
  using: node20
  main: dist/index.js

inputs:
  confFile:
    description: Your configuration file in the type of JSON.
