name: quote-box-zh_tw
author: Yu-huan Kuo <touch@rnmeow.com>
description: Get a quote and save as a file, API by Elegant TW. Works with GitHub Gist.
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'file-text'
  color: 'yellow'
