name: Update Gist

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 * * * *

jobs:
  # Gist Update
  update:
    # Use Ubuntu 22.04 LTS
    runs-on: ubuntu-22.04
    env:
      CATEGORY: dfgk
      FILE_NAME: 🌧 Hitokoto
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
      GIST_ID: 8277475f43f2054b4b7f8a51f24d41e7
    steps:
    # Step I
    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: 1.20.2
    # Step II
    - name: Checkout
      uses: actions/checkout@v3
    # Step III
    - name: Execute
      run: go run .

# Authored by @kuohuanhuan.
