name: Update Gist

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 * * * *

jobs:
  # Gist Update
  update:
    # Use Ubuntu 22.04 LTS
    runs-on: ubuntu-22.04
    env:
      CATEGORY: dik
      FILE_NAME: 🌧 Hitokoto
      GIST_ID: 8277475f43f2054b4b7f8a51f24d41e7
    steps:
    # Step I
    - name: Setup Deno
      uses: denoland/setup-deno@v1
      with:
        deno-version: v1.36.0
    # Step II
    - name: Checkout
      uses: actions/checkout@v4
    # Step III
    - name: Receive
      run: deno run --allow-read --allow-write --allow-net --allow-env index.ts
    # Step IV
    - name: Sync
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GH_TOKEN }}
        gist_id: ${{ env.GIST_ID }}
        gist_file_name: ${{ env.FILE_NAME }}
        file_path: dist/hitokoto.txt
        file_type: text

# Authored by rnmeow, licensed under MIT License.
